print(True and True)
print(True and False)
print(True or False)
print(False or False)
print(not True)
print(not not True)
print(3 < 5 and 8 > 2)
print(10 > 2 and False)
print("Hello" == "Hell0" or 5 == 7)
print(not("10" == 10))
